In [4]:
import pandas as pd
import numpy as np

#%%
import matplotlib.font_manager as font_manager
import matplotlib as mpl
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns


#폰트
font_dir = ['C:/mini_1/ye/fonts'] 
for font in font_manager.findSystemFonts(fontpaths=font_dir):
    print(mpl.font_manager.FontProperties(fname = font).get_name()) #이름확인
    font_manager.fontManager.addfont(font) #추가

    
# Set font family globally
mpl.rcParams['font.family'] = 'Gothic A1'
print(mpl.rcParams['font.family'])





#파일 불러오기
age = pd.read_csv("Tax/age.csv", encoding='euc-kr')
age

Gothic A1
['Gothic A1']

,업종명,영문명,30세 미만,30세 이상,40세 이상,50세 이상,60세 이상
0,가구점,Furniture Shop,102,197,276,230,96
1,가전제품수리점,Home Appliance Repair Shop,396,1145,1352,718,245
2,가전제품판매점,Electrical Appliances Shop,75,207,305,254,112
3,간이주점,Pub,256,425,413,455,185
4,간판광고물업,Manufacture of Signs and Advertisements,43,103,190,122,38
...,...,...,...,...,...,...,...
95,호프전문점,Beer Bar,752,1240,1570,1467,571
96,화장품가게,Cosmetics Shop,1036,1964,2125,1570,773
97,휴대폰가게,Mobile Phone Shop,1198,1781,792,364,199
98,LPG 충전소,LPG Station,8,14,25,88,21
99,pc방,PC Room,249,725,884,615,246

In [5]:
#복사본
age_c = age.copy()
age_c

,업종명,영문명,30세 미만,30세 이상,40세 이상,50세 이상,60세 이상
0,가구점,Furniture Shop,102,197,276,230,96
1,가전제품수리점,Home Appliance Repair Shop,396,1145,1352,718,245
2,가전제품판매점,Electrical Appliances Shop,75,207,305,254,112
3,간이주점,Pub,256,425,413,455,185
4,간판광고물업,Manufacture of Signs and Advertisements,43,103,190,122,38
...,...,...,...,...,...,...,...
95,호프전문점,Beer Bar,752,1240,1570,1467,571
96,화장품가게,Cosmetics Shop,1036,1964,2125,1570,773
97,휴대폰가게,Mobile Phone Shop,1198,1781,792,364,199
98,LPG 충전소,LPG Station,8,14,25,88,21
99,pc방,PC Room,249,725,884,615,246

In [8]:
#칼럼, 로우 확인
print(age_c.columns)
print(age_c.index)

Index(['업종명', '영문명', '30세 미만', '30세 이상', '40세 이상', '50세 이상', '60세 이상'], dtype='object')
RangeIndex(start=0, stop=100, step=1)

In [13]:
#인덱스 업종명으로 바꾸기
age_c.set_index('업종명 ', drop=True, inplace = True)
age_c

KeyError: "None of ['업종명 '] are in the columns"

In [14]:
age_c

,영문명,30세 미만,30세 이상,40세 이상,50세 이상,60세 이상
업종명,,,,,,
가구점,Furniture Shop,102,197,276,230,96
가전제품수리점,Home Appliance Repair Shop,396,1145,1352,718,245
가전제품판매점,Electrical Appliances Shop,75,207,305,254,112
간이주점,Pub,256,425,413,455,185
간판광고물업,Manufacture of Signs and Advertisements,43,103,190,122,38
...,...,...,...,...,...,...
호프전문점,Beer Bar,752,1240,1570,1467,571
화장품가게,Cosmetics Shop,1036,1964,2125,1570,773
휴대폰가게,Mobile Phone Shop,1198,1781,792,364,199
LPG 충전소,LPG Station,8,14,25,88,21
pc방,PC Room,249,725,884,615,246

In [17]:
age_c.drop('영문명', axis = 1, inplace = True)

KeyError: "['영문명'] not found in axis"

In [18]:
age_c

         30세 미만  30세 이상  40세 이상  50세 이상  60세 이상
업종명
가구점         102     197     276     230      96
가전제품수리점     396    1145    1352     718     245
가전제품판매점      75     207     305     254     112
간이주점        256     425     413     455     185
간판광고물업       43     103     190     122      38
...         ...     ...     ...     ...     ...
호프전문점       752    1240    1570    1467     571
화장품가게      1036    1964    2125    1570     773
휴대폰가게      1198    1781     792     364     199
LPG 충전소       8      14      25      88      21
pc방         249     725     884     615     246

[100 rows x 5 columns]

In [20]:
# age_c["30세 미만"]

# colors = ['yellowgreen', 'gold', 'lightskyblue', 'lightcoral', 'red']
# labels = ['Man', 'Woman', 'Prefer not to say', 'Non-binary, genderqueer, or gender non-conforming', 'Or, in your own words:']


# plt.title("Which of the following describe you, if any? Please check all that apply")
# plt.pie(count_g, labels = labels, colors = colors, autopct = '%1.1f%%', startangle = 180)
# plt.axis('equal')
# plt.show()

업종명
가구점         102
가전제품수리점     396
가전제품판매점      75
간이주점        256
간판광고물업       43
           ...
호프전문점       752
화장품가게      1036
휴대폰가게      1198
LPG 충전소       8
pc방         249
Name: 30세 미만, Length: 100, dtype: int64

In [22]:
age_c = age_c.T

In [23]:
age_c

업종명,가구점,가전제품수리점,가전제품판매점,간이주점,간판광고물업,감정평가사,건강보조식품가게,건어물가게,건축사,결혼상담소,...,피부관리업,피부ㆍ비뇨기과 의원,한방병원ㆍ한의원,한식전문점,헬스클럽,호프전문점,화장품가게,휴대폰가게,LPG 충전소,pc방
30세 미만,102,396,75,256,43,0,200,77,5,33,...,2559,5,55,10388,386,752,1036,1198,8,249
30세 이상,197,1145,207,425,103,18,474,161,260,67,...,3536,180,416,17860,878,1240,1964,1781,14,725
40세 이상,276,1352,305,413,190,60,700,271,456,104,...,2122,100,238,20568,375,1570,2125,792,25,884
50세 이상,230,718,254,455,122,25,692,301,210,95,...,984,38,165,19787,111,1467,1570,364,88,615
60세 이상,96,245,112,185,38,34,480,296,69,80,...,292,19,48,10718,71,571,773,199,21,246

In [ ]:
colors = ['yellowgreen', 'gold', 'lightskyblue', 'lightcoral', 'red']
# labels = ['Man', 'Woman', 'Prefer not to say', 'Non-binary, genderqueer, or gender non-conforming', 'Or, in your own words:']


plt.title("Which of the following describe you, if any? Please check all that apply")
# plt.pie(count_g, labels = labels, colors = colors, autopct = '%1.1f%%', startangle = 180)
# plt.axis('equal')
# plt.show()