In [1]:
import requests
import json
import pandas as pd
import numpy as np
from pandas.io.json import json_normalize
import os
import webbrowser
import folium
from folium import plugins
print(folium.__version__)

0.14.0

In [2]:
state_geo = 'TL_SCCO_CTPRVN.json'

In [ ]:
location = pd.read_csv("Tax/location.csv", encoding='cp949')

In [8]:
state_unemployment = 'Tax/location.csv'
state_data = pd.read_csv(state_unemployment, encoding = 'euc-kr')
state_data.columns = ['서울', '부산', '대전']
state_data['서울'] = state_data.서울.map(lambda x : str(x).zfill(5))
state_data.head(1)

ValueError: Length mismatch: Expected axis has 20 elements, new values have 3 elements

In [13]:
import numpy as np
import pandas as pd
import folium
import webbrowser
import json

In [210]:
csvFile = 'Tax/location.csv'
SiDodf = pd.read_csv(csvFile, encoding = 'euc-kr')
SiDodf

,업종명,영문명,합계,서울,인천,경기,강원,대전,충북,충남,세종,광주,전북,전남,대구,경북,부산,울산,경남,제주
0,가구점,Furniture Shop,901,98,46,343,24,22,23,40,9,26,45,22,31,48,47,14,43,20
1,가전제품수리점,Home Appliance Repair Shop,3856,603,312,1227,99,134,101,185,28,107,143,111,169,112,239,63,199,24
2,가전제품판매점,Electrical Appliances Shop,953,152,53,298,28,29,25,45,7,21,37,34,22,48,51,18,56,29
3,간이주점,Pub,1734,424,131,464,41,15,67,69,7,25,40,51,42,42,120,24,151,21
4,간판광고물업,Manufacture of Signs and Advertisements,496,79,16,163,17,8,18,26,1,11,14,22,22,29,25,11,26,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,호프전문점,Beer Bar,5600,866,306,1265,221,158,321,295,29,464,259,406,73,201,279,78,263,116
96,화장품가게,Cosmetics Shop,7468,1214,375,2068,213,251,191,319,47,255,319,218,379,414,401,206,499,99
97,휴대폰가게,Mobile Phone Shop,4334,701,331,1164,139,143,127,241,22,105,158,101,218,168,273,128,286,29
98,LPG 충전소,LPG Station,156,7,9,40,8,11,8,18,0,3,14,2,0,11,6,1,18,0
99,pc방,PC Room,2719,387,175,808,98,53,126,144,13,227,111,98,71,116,87,52,99,54

In [211]:
del SiDodf["업종명"]

In [212]:
del SiDodf["합계"]

In [213]:
SiDodf.reset_index(drop=True, inplace=True)

In [214]:
SiDodf = SiDodf.T
SiDodf

,0,1,2,3,4,5,6,7,8,9,...,90,91,92,93,94,95,96,97,98,99
영문명,Furniture Shop,Home Appliance Repair Shop,Electrical Appliances Shop,Pub,Manufacture of Signs and Advertisements,Appraiser,Health Additive Food Shop,Dried Fish Shop,Architect,Marriage Brokerage Business,...,Skin Beauty Shop,Dermatology·Urology Clinic,Oriental Medical Hospital·Clinic,Korean Food Restaurant,Fitness Center,Beer Bar,Cosmetics Shop,Mobile Phone Shop,LPG Station,PC Room
서울,98,603,152,424,79,29,508,108,326,121,...,1585,147,251,10499,478,866,1214,701,7,387
인천,46,312,53,131,16,6,121,85,24,13,...,596,14,42,4558,95,306,375,331,9,175
경기,343,1227,298,464,163,46,607,217,222,60,...,2564,67,256,18256,452,1265,2068,1164,40,808
강원,24,99,28,41,17,3,77,85,28,10,...,247,4,15,3191,54,221,213,139,8,98
대전,22,134,29,15,8,4,93,15,12,10,...,276,6,26,2438,53,158,251,143,11,53
충북,23,101,25,67,18,5,61,17,36,6,...,281,7,13,3010,45,321,191,127,8,126
충남,40,185,45,69,26,4,181,58,30,12,...,346,3,27,3869,63,295,319,241,18,144
세종,9,28,7,7,1,1,13,5,9,2,...,57,4,10,535,15,29,47,22,0,13
광주,26,107,21,25,11,3,77,23,29,19,...,453,7,28,2467,40,464,255,105,3,227
전북,45,143,37,40,14,0,137,40,30,17,...,314,9,27,2886,36,259,319,158,14,111
전남,22,111,34,51,22,2,60,122,36,12,...,365,6,24,3188,33,406,218,101,2,98
대구,31,169,22,42,22,5,105,28,43,27,...,379,23,49,3926,74,73,379,218,0,71
경북,48,112,48,42,29,1,128,89,28,13,...,389,7,27,5087,56,201,414,168,11,116
부산,47,239,51,120,25,10,142,83,45,30,...,617,22,66,5011,147,279,401,273,6,87
울산,14,63,18,24,11,6,51,26,18,11,...,210,4,13,2283,29,78,206,128,1,52
경남,43,199,56,151,26,11,149,100,43,14,...,654,8,40,6329,113,263,499,286,18,99
제주,20,24,29,21,8,1,36,6,41,2,...,160,4,8,1805,38,116,99,29,0,54

In [215]:
SiDodf["area"] = pd.Series(["area", "Seoul", "Incheon", "Gyeonggi-do", "Gangwon-do", "Daejeon", "Chungcheongbuk-do", "Chungcheongnam-do", "Sejongsi", "Gwangju", "Jeollabuk-do", "Jeollanam-do", "Daegu", "Gyeongsangbuk-do", "Busan", "Ulsan", "Gyeongsangnam-do", "Jeju-do"], index=SiDodf.index)

In [216]:
SiDodf

,0,1,2,3,4,5,6,7,8,9,...,91,92,93,94,95,96,97,98,99,area
영문명,Furniture Shop,Home Appliance Repair Shop,Electrical Appliances Shop,Pub,Manufacture of Signs and Advertisements,Appraiser,Health Additive Food Shop,Dried Fish Shop,Architect,Marriage Brokerage Business,...,Dermatology·Urology Clinic,Oriental Medical Hospital·Clinic,Korean Food Restaurant,Fitness Center,Beer Bar,Cosmetics Shop,Mobile Phone Shop,LPG Station,PC Room,area
서울,98,603,152,424,79,29,508,108,326,121,...,147,251,10499,478,866,1214,701,7,387,Seoul
인천,46,312,53,131,16,6,121,85,24,13,...,14,42,4558,95,306,375,331,9,175,Incheon
경기,343,1227,298,464,163,46,607,217,222,60,...,67,256,18256,452,1265,2068,1164,40,808,Gyeonggi-do
강원,24,99,28,41,17,3,77,85,28,10,...,4,15,3191,54,221,213,139,8,98,Gangwon-do
대전,22,134,29,15,8,4,93,15,12,10,...,6,26,2438,53,158,251,143,11,53,Daejeon
충북,23,101,25,67,18,5,61,17,36,6,...,7,13,3010,45,321,191,127,8,126,Chungcheongbuk-do
충남,40,185,45,69,26,4,181,58,30,12,...,3,27,3869,63,295,319,241,18,144,Chungcheongnam-do
세종,9,28,7,7,1,1,13,5,9,2,...,4,10,535,15,29,47,22,0,13,Sejongsi
광주,26,107,21,25,11,3,77,23,29,19,...,7,28,2467,40,464,255,105,3,227,Gwangju
전북,45,143,37,40,14,0,137,40,30,17,...,9,27,2886,36,259,319,158,14,111,Jeollabuk-do
전남,22,111,34,51,22,2,60,122,36,12,...,6,24,3188,33,406,218,101,2,98,Jeollanam-do
대구,31,169,22,42,22,5,105,28,43,27,...,23,49,3926,74,73,379,218,0,71,Daegu
경북,48,112,48,42,29,1,128,89,28,13,...,7,27,5087,56,201,414,168,11,116,Gyeongsangbuk-do
부산,47,239,51,120,25,10,142,83,45,30,...,22,66,5011,147,279,401,273,6,87,Busan
울산,14,63,18,24,11,6,51,26,18,11,...,4,13,2283,29,78,206,128,1,52,Ulsan
경남,43,199,56,151,26,11,149,100,43,14,...,8,40,6329,113,263,499,286,18,99,Gyeongsangnam-do
제주,20,24,29,21,8,1,36,6,41,2,...,4,8,1805,38,116,99,29,0,54,Jeju-do

In [217]:
SiDodf.reset_index(inplace=True)

In [218]:
SiDodf = SiDodf.rename(columns=SiDodf.iloc[0])
SiDodf = SiDodf[1:]

In [219]:
SiDodf

,영문명,Furniture Shop,Home Appliance Repair Shop,Electrical Appliances Shop,Pub,Manufacture of Signs and Advertisements,Appraiser,Health Additive Food Shop,Dried Fish Shop,Architect,...,Dermatology·Urology Clinic,Oriental Medical Hospital·Clinic,Korean Food Restaurant,Fitness Center,Beer Bar,Cosmetics Shop,Mobile Phone Shop,LPG Station,PC Room,area
1,서울,98,603,152,424,79,29,508,108,326,...,147,251,10499,478,866,1214,701,7,387,Seoul
2,인천,46,312,53,131,16,6,121,85,24,...,14,42,4558,95,306,375,331,9,175,Incheon
3,경기,343,1227,298,464,163,46,607,217,222,...,67,256,18256,452,1265,2068,1164,40,808,Gyeonggi-do
4,강원,24,99,28,41,17,3,77,85,28,...,4,15,3191,54,221,213,139,8,98,Gangwon-do
5,대전,22,134,29,15,8,4,93,15,12,...,6,26,2438,53,158,251,143,11,53,Daejeon
6,충북,23,101,25,67,18,5,61,17,36,...,7,13,3010,45,321,191,127,8,126,Chungcheongbuk-do
7,충남,40,185,45,69,26,4,181,58,30,...,3,27,3869,63,295,319,241,18,144,Chungcheongnam-do
8,세종,9,28,7,7,1,1,13,5,9,...,4,10,535,15,29,47,22,0,13,Sejongsi
9,광주,26,107,21,25,11,3,77,23,29,...,7,28,2467,40,464,255,105,3,227,Gwangju
10,전북,45,143,37,40,14,0,137,40,30,...,9,27,2886,36,259,319,158,14,111,Jeollabuk-do
11,전남,22,111,34,51,22,2,60,122,36,...,6,24,3188,33,406,218,101,2,98,Jeollanam-do
12,대구,31,169,22,42,22,5,105,28,43,...,23,49,3926,74,73,379,218,0,71,Daegu
13,경북,48,112,48,42,29,1,128,89,28,...,7,27,5087,56,201,414,168,11,116,Gyeongsangbuk-do
14,부산,47,239,51,120,25,10,142,83,45,...,22,66,5011,147,279,401,273,6,87,Busan
15,울산,14,63,18,24,11,6,51,26,18,...,4,13,2283,29,78,206,128,1,52,Ulsan
16,경남,43,199,56,151,26,11,149,100,43,...,8,40,6329,113,263,499,286,18,99,Gyeongsangnam-do
17,제주,20,24,29,21,8,1,36,6,41,...,4,8,1805,38,116,99,29,0,54,Jeju-do

In [220]:
del SiDodf["영문명"]

In [221]:
SiDodf.to_csv("Tax/location_for_map.csv", encoding="utf-8", index=False)

,Furniture Shop,Home Appliance Repair Shop,Electrical Appliances Shop,Pub,Manufacture of Signs and Advertisements,Appraiser,Health Additive Food Shop,Dried Fish Shop,Architect,Marriage Brokerage Business,...,Dermatology·Urology Clinic,Oriental Medical Hospital·Clinic,Korean Food Restaurant,Fitness Center,Beer Bar,Cosmetics Shop,Mobile Phone Shop,LPG Station,PC Room,area
0,98,603,152,424,79,29,508,108,326,121,...,147,251,10499,478,866,1214,701,7,387,Seoul
1,46,312,53,131,16,6,121,85,24,13,...,14,42,4558,95,306,375,331,9,175,Incheon
2,343,1227,298,464,163,46,607,217,222,60,...,67,256,18256,452,1265,2068,1164,40,808,Gyeonggi-do
3,24,99,28,41,17,3,77,85,28,10,...,4,15,3191,54,221,213,139,8,98,Gangwon-do
4,22,134,29,15,8,4,93,15,12,10,...,6,26,2438,53,158,251,143,11,53,Daejeon
5,23,101,25,67,18,5,61,17,36,6,...,7,13,3010,45,321,191,127,8,126,Chungcheongbuk-do
6,40,185,45,69,26,4,181,58,30,12,...,3,27,3869,63,295,319,241,18,144,Chungcheongnam-do
7,9,28,7,7,1,1,13,5,9,2,...,4,10,535,15,29,47,22,0,13,Sejongsi
8,26,107,21,25,11,3,77,23,29,19,...,7,28,2467,40,464,255,105,3,227,Gwangju
9,45,143,37,40,14,0,137,40,30,17,...,9,27,2886,36,259,319,158,14,111,Jeollabuk-do
10,22,111,34,51,22,2,60,122,36,12,...,6,24,3188,33,406,218,101,2,98,Jeollanam-do
11,31,169,22,42,22,5,105,28,43,27,...,23,49,3926,74,73,379,218,0,71,Daegu
12,48,112,48,42,29,1,128,89,28,13,...,7,27,5087,56,201,414,168,11,116,Gyeongsangbuk-do
13,47,239,51,120,25,10,142,83,45,30,...,22,66,5011,147,279,401,273,6,87,Busan
14,14,63,18,24,11,6,51,26,18,11,...,4,13,2283,29,78,206,128,1,52,Ulsan
15,43,199,56,151,26,11,149,100,43,14,...,8,40,6329,113,263,499,286,18,99,Gyeongsangnam-do
16,20,24,29,21,8,1,36,6,41,2,...,4,8,1805,38,116,99,29,0,54,Jeju-do

In [232]:
def give_me_the_awesome_map(column, bins):
    # 앞서 전처리한 데이터를 불러옵니다.
    csvFile = 'Tax/location_for_map.csv'
    SiDodf = pd.read_csv(csvFile, encoding = 'utf-8')

    # 시도 행정구역에 대한 json파일을 지정합니다.
    SiDo_geo = 'https://raw.githubusercontent.com/suanlab/dataset/master/skorea-provinces-2018-geo.json'
    
    # 기본 맵을 설정합니다.
    m = folium.Map(location = [36.45, 127.42],
                    tiles = "OpenStreetMap", zoom_start = 8)
    
    # 시도에 맞는 데이터를 맵핑하여 색상으로 인코딩한 레이어를 생성합니다.
    folium.Choropleth(
        geo_data = SiDo_geo,
        name = '업종별 분포 지도',
        data = SiDodf,
        columns = ['area', column],
        key_on='feature.properties.name_eng',
        fill_color = 'PuRd',
        fill_opacity = 0.7,
        bins=bins,
        line_opacity = 0.2,
        legent_name = "개업수").add_to(m)
    
    # 지도에 레이어 컨트롤을 추가합니다.
    folium.LayerControl().add_to(m)
    
    m.save(f'maps/{column.replace(" ", "_")}_map.html')
    # 저장한 파일을 열어봅니다.
    # webbrowser.open(f'maps/{column.replace(" ", "_")}_map.html')

In [235]:
# 파일을 다시 불러옵니다.
SiDodf2 = pd.read_csv('Tax/location_for_map.csv', encoding = 'utf-8')
display(SiDodf)

,Furniture Shop,Home Appliance Repair Shop,Electrical Appliances Shop,Pub,Manufacture of Signs and Advertisements,Appraiser,Health Additive Food Shop,Dried Fish Shop,Architect,Marriage Brokerage Business,...,Skin Beauty Shop,Dermatology·Urology Clinic,Oriental Medical Hospital·Clinic,Korean Food Restaurant,Fitness Center,Beer Bar,Cosmetics Shop,Mobile Phone Shop,LPG Station,PC Room
0,98,603,152,424,79,29,508,108,326,121,...,1585,147,251,10499,478,866,1214,701,7,387
1,46,312,53,131,16,6,121,85,24,13,...,596,14,42,4558,95,306,375,331,9,175
2,343,1227,298,464,163,46,607,217,222,60,...,2564,67,256,18256,452,1265,2068,1164,40,808
3,24,99,28,41,17,3,77,85,28,10,...,247,4,15,3191,54,221,213,139,8,98
4,22,134,29,15,8,4,93,15,12,10,...,276,6,26,2438,53,158,251,143,11,53
5,23,101,25,67,18,5,61,17,36,6,...,281,7,13,3010,45,321,191,127,8,126
6,40,185,45,69,26,4,181,58,30,12,...,346,3,27,3869,63,295,319,241,18,144
7,9,28,7,7,1,1,13,5,9,2,...,57,4,10,535,15,29,47,22,0,13
8,26,107,21,25,11,3,77,23,29,19,...,453,7,28,2467,40,464,255,105,3,227
9,45,143,37,40,14,0,137,40,30,17,...,314,9,27,2886,36,259,319,158,14,111
10,22,111,34,51,22,2,60,122,36,12,...,365,6,24,3188,33,406,218,101,2,98
11,31,169,22,42,22,5,105,28,43,27,...,379,23,49,3926,74,73,379,218,0,71
12,48,112,48,42,29,1,128,89,28,13,...,389,7,27,5087,56,201,414,168,11,116
13,47,239,51,120,25,10,142,83,45,30,...,617,22,66,5011,147,279,401,273,6,87
14,14,63,18,24,11,6,51,26,18,11,...,210,4,13,2283,29,78,206,128,1,52
15,43,199,56,151,26,11,149,100,43,14,...,654,8,40,6329,113,263,499,286,18,99
16,20,24,29,21,8,1,36,6,41,2,...,160,4,8,1805,38,116,99,29,0,54

In [ ]:
# 수치 값이 아닌 column area를 지웁니다.
del SiDodf2["area"]

In [233]:
# 수치 값을 갖는 전체 컬럼에 대해 반복
for column in SiDodf.columns:
    give_me_the_awesome_map(column, 
                            # 백분위 수 중 10분위, 20분위, 30분위, 40분위, 50분위, ... 100분위까지 범위를 갖는 bins 구합니다.
                            [np.percentile(SiDodf[column], _) for _ in range(0, 101, 10)])